// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwmOAJr9UJEa78MyRjpMze9V-2Ps5HxEQ',
    appId: '1:142461616116:android:ba250e499396628aa4c3a1',
    messagingSenderId: '142461616116',
    projectId: 'map-app-72943',
    storageBucket: 'map-app-72943.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQz0Owawdpy84O7pRsDJtHH3NhN-vwooY',
    appId: '1:142461616116:ios:1abd13e882181609a4c3a1',
    messagingSenderId: '142461616116',
    projectId: 'map-app-72943',
    storageBucket: 'map-app-72943.firebasestorage.app',
    androidClientId: '142461616116-06o57q3fk9micv6sv3688sp1akunf21v.apps.googleusercontent.com',
    iosClientId: '142461616116-sr5r4l18bkej46c1j9qk9g3qi152jcr0.apps.googleusercontent.com',
    iosBundleId: 'com.example.mapapp',
  );

}